### ISSUE TITLE
[Enhancement] PLEX for PKG

### ISSUE THREAD

**Issue by pepitopajas** [LightningMods/PS4-Store#12]
Hello, your store is like a plex (media content server) for PKG

Can you develop an application, so that the user can create their own store, either through a nas or cloud?

**Comment by LightningMods** [comment]
Yes a Store local CDN tool is scheduled to be released with a new store update tomorrow night along with a YouTube video

**Comment by LightningMods** [comment]
New Store Update 2.3 is released along with a CDN windows tool

https://twitter.com/LightningMods_/status/1506823722174644224?s=20&t=4Wc-wx2Ya9O6dQILW1oWOw

https://twitter.com/LightningMods_/status/1506823737320083461?s=20&t=QZ5z6ePmlcCd7ZS7-YusPQ
