### ISSUE TITLE
Network Path on Package Page Has a Typo

### ISSUE THREAD

**Issue by AwesomeAustn** [LightningMods/PS4-Store#13]
The server app finds the packages, and lists them in the Store, but the path is modified on the package page, and won't download. It removes the first letter after \\

Example:
Sever app path
`\\UNRAID\Games`

Package page in the Store
`http://IP/NRAID/Game.pkg`

**Comment by LightningMods** [comment]
Hello, this is the wrong repo for your issue but also you have to put //server/... URLs cannot have \ it's an illegal character

**Comment by AwesomeAustn** [comment]
Whoops. It's meant to go to https://github.com/LightningMods/Store-CDN-Tool
