### ISSUE TITLE
How to self host a Store Server on Linux?

### ISSUE THREAD

**Issue by elbowz** [LightningMods/PS4-Store#14]
I guess the only solution was hbstore-cdn.
...but it seems no longer works https://github.com/sleirsgoevy/hbstore-cdn/issues/6, right?

Thanks!

**Comment by LightningMods** [comment]
firstly this is the wrong repo for that, 2nd that is out of date

**Comment by elbowz** [comment]
I'm really sorry for have wasted your time...

I was asking referring to your README:

> the ELFs in the release section are ONLY for CDNs or for **locally hosting** a Store Server

What and How you mean for **locally hosting** ?

> 2nd that is out of date

Do you refer to hb-store? Yeah, I have linked the issue that confirm.

Sorry again for my issue...and thanks again for your time!
