### ISSUE TITLE
Store Crash

### ISSUE THREAD

**Issue by hyde119** [LightningMods/PS4-Store#15]
I was dumping a game and it seems that the dump didn't complete all they way. Now whenever I try to access the store I receive the following error: 

_The Store Loader has encountered an error

For more info check: /user/app/NPXS39041/logs/loader.log The App will now Close_

When reviewing the log it don't display much more information: 

[STORE_GL_Loader:main:390] -----  All Internal Modules Loaded  -----
------------------------ Store Loader[GL] Compiled Time: Feb  6 2022 @ 12:33:05 EST -------------------------
[STORE_GL_Loader:main:392] -----  STORE Version: 1.4-V-2022-02-06T12:33:05  -----
----------------------------------------------- -------------------------
path /mnt/usb0/settings.ini, errno No such file or directorypath /user/app/NPXS39041/settings.ini, errno No such file or directory[STORE_GL_Loader:main:419] ----- APP INI Not Found, Making ini ---
[STORE_GL_Loader:main:453] ----- CDN Url = http://api.pkg-zone.com ---
[STORE_GL_Loader:pingtest:124] ----- sceHttpsSetSslCallback() Success ---
[STORE_GL_Loader:pingtest:133] ----- sceHttpCreateConnectionWithURL() Success ---
[STORE_GL_Loader:main:460] ----- Ping Successfully ---
[loader.log](https://github.com/LightningMods/PS4-Store/files/8403785/loader.log)

connection errror
[STORE_GL_Loader:download_file:303] ----- status code = 530 ---
The Store Loader has encountered an error

For more info check: /user/app/NPXS39041/logs/loader.log The App will now Close
Rejailing App

**Comment by LightningMods** [comment]
Can you confirm you still have this issue?

**Comment by hyde119** [comment]
It appears to have been fixed. Thank you very much. Is there something on my end that messed it up?

**Comment by manoloturbo** [comment]
Can you share how you fix it?. Im having the same issue
