### ISSUE TITLE
Cyberpunk 2077: patch dump stucks at lang_ko_voice.archive file

### ISSUE THREAD

**Issue by padremayi** [LightningMods/PS4-Store#16]
Cyberpunk 2077, game dump was completed fine, patch dump stucks at lang_ko_voice.archive file at 53% of the total.

Last lines of log are these:

```
2022-07-01 23:10:29 INFO  source/pfs.cpp:37: ---- name: /mnt/usb0/CUSA18278-patch//archive/ps4/content/lang_ko_voice.archive, ptr 679780000, sz 3879149568, FD: 20
2022-07-01 23:10:29 INFO  source/pfs.cpp:43: copying 2097152 bytes ix: 0 size: 3879149568 pfs prog: 27595100160/51563729435
```

In the log there are these ERROR lines at the beginning of each dump (game, then patch):

```
2022-07-01 23:01:02 ERROR source/dump.cpp:80: Unable to create dumping semaphore!
2022-07-01 23:01:02 ERROR source/pkg.cpp:207: Unable to open/create output subdirectory
2022-07-01 23:01:03 ERROR source/pkg.cpp:207: Unable to open/create output subdirectory
2022-07-01 23:01:03 ERROR source/pkg.cpp:207: Unable to open/create output subdirectory
```

Using [ftpdump](https://github.com/hippie68/ftpdump) the process terminates without any errors

**Comment by LightningMods** [comment]
hello that happens if you don't have all the Game languages installed, ftpdump will dump a corrupted file, the store will not and so it stalls, try to install the langs via the games settings and try again

**Comment by padremayi** [comment]
Hi, I read that section in the main page but I don't understand the approach. I changed the system language to korean and in some way the game has installed the relative voice language.

Now the problem is present with lang_**de**_voice.archive.

[ftpdump](https://github.com/hippie68/ftpdump) dumps only the available languages, so if the system language is set to english it skips all the other VOICE languages (not the text ones).

It seems that your tool wants to dump also files that, at the moment, doesn't exist. Is it true?

Meanwhile I'll try to search the missing languages inside game settings.

Thanks for the tip to search inside the game

**Comment by padremayi** [comment]
I confirm that there is the possibility to add some languages throught in-game settings. After that the dump is performed without any errors. Otherwise you have to change system language.

But my previous question remains: why the application tries to dump a language that is not installed?

**Comment by LightningMods** [comment]
It tries to dump the whole game via the PFS image that's mounted when you start the game, ftpdump downloads the whole sandbox directory, just so happens the PFS image tells us theres files that don't exist yet

**Comment by padremayi** [comment]
It makes sense, really appreciate your explanation
