### ISSUE TITLE
The app will crash when pressing “X” to open LogMeIn Hamachi

### ISSUE THREAD

**Issue by realrodri** [LightningMods/PS4-Store#3]
The app is crashing when I’m trying to get the screen to show me the “Download” button of LogMeIn Hamachi.

Error: CE-34878-0
PS4’s version: 6.72
App’s version: Latest

**Comment by LightningMods** [comment]
Try searching for it in the app using "search for" and test it

**Comment by realrodri** [comment]
Fixed! Thanks. Also, when I install it and run it, throws me an error that I'm not on a supported version (whether is 6.72 or 7.02) although, I'm on 6.72. Kind of weird. Closing the thread, as it has been solved.

**Comment by sleirsgoevy** [comment]
TL;DR: use Mira, not HEN.

Regarding the "wrong fw" screen: this app currently requires you to use Mira, not HEN. It should have reported that properly, but some HEN payloads include a firmware spoof which makes it misdetect an unsupported firmware and show the wrong error message.
