### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by godreborn** [LightningMods/PS4-Store#5]
I'm trying to learn how to compile ps4 projects, but I have an issue when trying to compile the store.  it says this:

C:\Users\GODREBORN\Desktop\PS4-Store-master\Store>make
clang -c source/GLES2_ani.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -Wno-zero-length-array -Wno-format-pedantic -I. -Iinclude -IC:\ps4sdk/usr/include -IC:\ps4sdk/usr/include/c++/v1 -IC:\ps4sdk/usr/include/orbis -IC:\ps4sdk/usr/include/orbis/freetype-gl -ffreestanding -nostdlib -nostdinc -fno-builtin -fno-stack-protector -D__PS4__ -IC:\OpenOrbis\PS4Toolchain/include -I C:\OpenOrbis\PS4Toolchain/include/sce -target x86_64-scei-ps4-elf -fPIE -D__PS4__ -D__ORBIS__ -o build/GLES2_ani.c.o
In file included from source/GLES2_ani.c:10:
In file included from include/defines.h:23:
include/utils.h:5:10: fatal error: 'pl_ini.h' file not found
#include <pl_ini.h>
^~~~~~~~~~
1 error generated.
make: *** [C:\ps4sdk/make/ps4sdk.mk:158: build/GLES2_ani.c.o] Error 1

I don't know where that file is.  I have ps4sdk as orbisdev, llvm installed, and open orbis as the ps4 sdk.  however, pl.ini.h doesn't seem to be anywhere in these three things.  am I missing a dependency somewhere?

**Comment by LightningMods** [comment]
Hello, it says you are using the `OpenOrbis` SDK, currently only the orbisdev sdk is supported (I recommend the docker container) for more of a 1 on 1 Convo

Join the discord: https://discord.gg/NGuqfhTu
