### ISSUE TITLE
Doesn't work on 9.0 JB

### ISSUE THREAD

**Issue by GitGitHubUser** [LightningMods/PS4-Store#7]
Hi,
I just tried to use it on a PS4 Pro 9.0 JB (CUH7200), but it exits with an error (something about /data/app/....). I used the 2.0 Store PKG file to install it. Please comment, many thanks!

**Comment by LightningMods** [comment]
For Any troubleshooting for the App you must provide the Log file via FTP from this dir: `/user/app/NPXS39041/log`

**Comment by LightningMods** [comment]
Please reply within 2 days or I'll close for inactivity

**Comment by GitGitHubUser** [comment]
Sorry, the error is CE-34878-0. After several retries it finally worked, thanks.

**Comment by LightningMods** [comment]
This issue is now resolved
